### PR TITLE
add social link to discuss.okfn.or

### PR DESCRIPTION
**Pull request by ppKrauss**
Add an icon in the *header-nav* superior bar, linking to appropriate folder at [discuss.okfn.org](https://discuss.okfn.org). For administrator, at `theme-options.php` page, add the "Discuss Page" field.

### CODE REVIEW

**Comment by morchickit** [comment]
@gocemitevski can we do it? It will help us to direct people to the discuss forum...

**Comment by gocemitevski** [comment]
@morchickit yes. Can you please describe what we need exactly, in more details?

>linking to appropriate folder

Does this mean that the link will be variable to the page/post content in WordPress?

**Comment by morchickit** [comment]
I believe that Peter just added here a social link in the header to OK Brasil Discuss forum. 
Is this possible? https://discuss.okfn.org

**Comment by gocemitevski** [comment]
@morchickit I already replied that it is possible. What I don't know at the moment is how complex the implementation should be. Will that be a static link, modifiable per site or would it change per page or post?

**Comment by morchickit** [comment]
Same link per site. Very static and simple

**Comment by ppKrauss** [comment]
Hi, thanks @morchickit and @gocemitevski. The social link that I added is a clone of others: you can configure the link address (see [the `_discuss_id`](https://github.com/okfn-brasil/wordpress-theme/commit/41a16e45f37876e079b079cfda88e2647162cc42) new option at commit).  

Please accept the fork or create a "testing version" and add it in your [Wordpress Multisite](https://codex.wordpress.org/Glossary#Multisite) administrator (we not have permission to add new Theme neither new theme-version).

**Comment by ppKrauss** [comment]
@morchickit if you waiting for me, you must to, first, [promote me to a team maintainer](https://help.github.com/articles/permission-levels-for-an-organization/). The message here, for me, is *"Only those with write access to this repository can merge pull requests"*.

**Comment by morchickit** [comment]
Waiting for @goce...

**Comment by pwalsh** [comment]
@gocemitevski please advise.

**Comment by gocemitevski** [comment]
Sorry for the delay. @morchickit I suggest that I add the language switcher above the post content to make it more visible, as it will definitely be not that visible if placed in the Sidebar. If we don't need the flags, we can formulate the block as a sentence -- see attachment below -- and make it more noticeable.

screenshot 1

cc @pwalsh

**Comment by ppKrauss** [comment]
Hi @gocemitevski and @morchickit ,



this is the effect, and each chapter can edit  its [local group link to Discuss.OKFN.ORG](https://discuss.okfn.org/c/local-groups). It is not a link to a *private brand*, **is an important advertising** to an open OKFN tool, and the [main local-group communication chanel](https://discuss.okfn.org/t/convencoes-adotadas-pela-okbr/3665/2)...  And it was a [legitime decision](https://discuss.okfn.org/t/procura-se-voluntario-para-a-equipe-tecnica-de-apoio-institucional/3931) of the local-group body to add this icon.
 
I not understand the problem to add [this 8 lines of necessary code](https://github.com/okfn-brasil/wordpress-theme/commit/41a16e45f37876e079b079cfda88e2647162cc42) to the wordpress-theme.

**Comment by pwalsh** [comment]
@gocemitevski your last answer seems unrelated to this PR.

@ppKrauss I don't follow you, sorry. I don't see anywhere that anyone said there is a problem, so please be patient for @gocemitevski and @morchickit to prioritise this with the various other things they are doing as part of their daily work. I hope it won't be too long.

**Comment by gocemitevski** [comment]
Sorry about the confusion. I somehow replied to the wrong issue, so I will delete that comment to not cause any more confusion.

@ppKrauss absolutely no problem. Will merge the code right away.

cc @pwalsh, @morchickit

**Comment by gocemitevski** [comment]
@morchickit the changes are now live on all OKI networks where this theme is used. Updating the Discuss link is possible through Appearance > Theme Options in the WordPress back-end.

cc @pwalsh @ppKrauss

**Pull request merged**
