### PR TITLE
Don't show title on the home page

### LINKED ISSUE #5: title only on first page
Check out http://okfn.be

There's home in `<h1>` on the first page. I cannot disable it. On the other pages, it's not there (which imo should be default behaviour)

Pieter

### PR DESCRIPTION
**Pull request by pietercolpaert**
Don't show this title: it's already on the page twice... no need for a third time.

Fixes #5

### CODE REVIEW

**Comment by nigelbabu** [comment]
Where is on the page once? The reason for this I thought is because in other pages, it's on the green bar. On the home page it's one step below. Thoughts?

**Comment by pietercolpaert** [comment]
screenshot from 2015-02-19 12 33 37

**Comment by smth** [comment]
My thoughts on this (not having seen the full page):

I agree that as it is it's pretty redundant, but it could easily be useful. Heading tags (especially h1s) are very important for SEO for example.

A simple suggestion would be that this page is renamed to something else (assuming this heading is driven by page title). For example "Welcome to Open Knowledge Belgium". The validity of this suggestion obviously depends on where else on the page the title is displayed.

Another option (involving some work) would be to include a setting to disable it via Wordpress admin.

Removing the heading from the template or hiding it with CSS are of course also options ;)

**Comment by pwalsh** [comment]
Closing because this is old and is being fixed as part of general work on the theme

**Pull request closed without merging**
